### ISSUE TITLE
Google Play Services Usage

### ISSUE THREAD

**Issue by xgear-public** [pubnative/pubnative-android-library#24]
Please provide more details in read me about Google Play Services dependencies. Which Google Play Services modules need pubnative android library to work well.

**Comment by cerberillo** [comment]
It's currently announced that It's neded to include the google play services version in theAndroidManifest in order to work well.

What do you want to know? PubNative uses google play services in order to open the google play dialog inside the app instead of redirecting through the browser to theplay store, so the user experience is more consistent inside the app.

**Comment by xgear-public** [comment]
Please check Table 1 at this page. https://developers.google.com/android/guides/setup
you can find list of google play services mouldes. I need to know which modules i need to use for pubnative android library. 
I prefer to use only modules that i need in my application instead of connecting whole google play services lib to project.

**Comment by cerberillo** [comment]
Thanks for your question xgear, but I don't understand your problem, the current library is only importing the necessary packages, including that `AndoridManifest.xml` line is not going to include the entire google play library, that's only an app needed value for the used modules.

Please, check the build.gradle file of the library to see the used libraries, in fact, you don't need to include them in your app, since using the library as a module would manage the used modules independently. 

Here you can see that the used one is the "ads" module for retrieving the android advertising id: 

https://github.com/pubnative/pubnative-android-library/blob/master/library/build.gradle#L26

And this is the point where it's being used:

https://github.com/pubnative/pubnative-android-library/blob/master/library/src/main/java/net/pubnative/library/util/IdUtil.java#L34

Cheers,
