### ISSUE TITLE
Cannot associate PubNativeListener events (onLoaded, onError) with an AdRequest that caused them

### ISSUE THREAD

**Issue by taras-puchko** [pubnative/pubnative-android-library#3]
Please pass AdRequest or AdHolder to the onLoaded and onError methods or allow specifying PubNativeListener per each showAd call.

**Comment by cerberillo** [comment]
Hi taras-puchko:

Thanks for your suggestion. We were thinking in doing something like that since a while. However this would change the whole workflow of the library in all our current clients, and as far as we don't want to break possible updates we need to evaluate this carefully. 

I can ensure you that we will take this into consideration for future releases.

Cheers!
